import type { SidebarItem } from './types'

export const SIDEBAR_CATALOG: SidebarItem[] = [
  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: MI DÍA
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'inicio',
    label: 'Inicio',
    href: '/admin',
    icon: 'Home',
    capa: 'troncal',
    estado: 'activo',
    espacio: 'mi-dia',
    grupo: 'Principal',
    orden: 10,
  },
  {
    id: 'mi-agenda',
    label: 'Mi agenda',
    href: '/admin/mi-agenda',
    icon: 'Calendar',
    capa: 'troncal',
    estado: 'proximamente',
    modulo_slug: 'eventos_calendario',
    espacio: 'mi-dia',
    grupo: 'Principal',
    orden: 20,
  },
  {
    id: 'notificaciones',
    label: 'Notificaciones',
    href: '/admin/notificaciones',
    icon: 'Bell',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'notificaciones',
    espacio: 'mi-dia',
    grupo: 'Principal',
    orden: 30,
  },
  {
    id: 'mis-tareas',
    label: 'Mis tareas',
    href: '/admin/mis-tareas',
    icon: 'CheckSquare',
    capa: 'troncal',
    estado: 'proximamente',
    modulo_slug: 'proyectos',
    espacio: 'mi-dia',
    grupo: 'Principal',
    orden: 40,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: OPERACIÓN
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: CRM —
  {
    id: 'personas',
    label: 'Personas',
    href: '/admin/personas',
    icon: 'Users',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'personas.read',
    espacio: 'operacion',
    grupo: 'CRM',
    orden: 10,
  },
  {
    id: 'entidades',
    label: 'Entidades',
    href: '/admin/entidades',
    icon: 'Building2',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'entidades.read',
    espacio: 'operacion',
    grupo: 'CRM',
    orden: 20,
  },
  {
    id: 'padrones',
    label: 'Padrones',
    href: '/admin/padrones',
    icon: 'UsersRound',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'personas.read',
    espacio: 'operacion',
    grupo: 'CRM',
    orden: 30,
  },

  // — GRUPO: Atención al Socio —
  {
    id: 'membresias',
    label: 'Membresías',
    href: '/admin/membresias',
    icon: 'IdCard',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'cuotas_recurrentes',
    espacio: 'operacion',
    grupo: 'Atención al Socio',
    orden: 40,
  },
  {
    id: 'cobranzas',
    label: 'Cobranzas',
    href: '/admin/finanzas/cuotas',
    icon: 'DollarSign',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'cuotas_recurrentes',
    espacio: 'operacion',
    grupo: 'Atención al Socio',
    orden: 50,
  },
  {
    id: 'comunicaciones',
    label: 'Comunicaciones',
    href: '/admin/comunicaciones',
    icon: 'MessageSquare',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'comunicaciones_masivas',
    espacio: 'operacion',
    grupo: 'Atención al Socio',
    orden: 60,
  },
  {
    id: 'pre-inscripciones',
    label: 'Pre-inscripciones',
    href: '/admin/pre-inscripciones',
    icon: 'UserPlus',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'pre_inscripciones',
    espacio: 'operacion',
    grupo: 'Atención al Socio',
    orden: 70,
  },

  // — GRUPO: Operación Deportiva —
  {
    id: 'equipos',
    label: 'Equipos',
    href: '/admin/equipos',
    icon: 'Users2',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'equipos',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 80,
  },
  {
    id: 'planificadores',
    label: 'Planificadores',
    href: '/admin/planificadores/semanal',
    icon: 'CalendarRange',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'planificadores',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 85,
  },
  {
    id: 'asistencias',
    label: 'Asistencias',
    href: '/admin/planificadores/semanal',
    icon: 'ClipboardCheck',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'asistencias',
    nota: 'Se gestionan desde cada evento del planificador.',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 90,
  },
  {
    id: 'entrenamientos',
    label: 'Entrenamientos',
    href: '/admin/planificadores/semanal?tipo=entrenamiento',
    icon: 'Dumbbell',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'entrenamientos',
    nota: 'Se planifican como eventos tipo entrenamiento.',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 100,
  },
  {
    id: 'partidos',
    label: 'Partidos',
    href: '/admin/competencias/partidos',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'partidos',
    nota: 'Listado de partidos del club desde competencias.',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 110,
  },
  {
    id: 'amistosos',
    label: 'Amistosos',
    href: '/admin/planificadores/semanal?tipo=amistoso',
    icon: 'Swords',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'amistosos',
    nota: 'Se planifican como eventos tipo amistoso.',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 120,
  },
  {
    id: 'competencias',
    label: 'Competencias y torneos',
    href: '/admin/competencias/torneos',
    icon: 'Award',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'torneos',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 130,
  },
  {
    id: 'salud',
    label: 'Salud / Lesiones',
    href: '/admin/salud',
    icon: 'Heart',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'datos_medicos',
    capability_requerida: 'ccbp.salud.read_basic',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 140,
  },
  {
    id: 'scouting',
    label: 'Scouting',
    href: '/admin/operaciones/scouting',
    icon: 'Search',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'scouting',
    capability_requerida: 'ccbp.scouting.read',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 150,
  },
  {
    id: 'trayectoria',
    label: 'Historial / Trayectoria',
    href: '/admin/personas',
    icon: 'History',
    capa: 'vertical_ccbp',
    estado: 'activo',
    capability_requerida: 'ccbp.plantel.read',
    nota: 'Se gestiona en el tab Trayectoria de cada persona.',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 160,
  },
  {
    id: 'disciplinas',
    label: 'Disciplinas',
    href: '/admin/disciplinas',
    icon: 'LayoutGrid',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    modulo_slug: 'disciplinas',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 170,
  },
  {
    id: 'tactica',
    label: 'Táctica',
    href: '/admin/planificadores/semanal?tipo=partido,amistoso',
    icon: 'Target',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'tactica',
    nota: 'Se configura desde cada partido/amistoso.',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 190,
  },
  {
    id: 'reservas',
    label: 'Reservas de canchas',
    href: '/admin/reservas',
    icon: 'LandPlot',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'reservas',
    espacio: 'operacion',
    grupo: 'Operación Deportiva',
    orden: 200,
  },

  // — GRUPO: Servicios al Socio —
  {
    id: 'acceso',
    label: 'Acceso al club',
    href: '/admin/acceso',
    icon: 'KeyRound',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'acceso',
    espacio: 'operacion',
    grupo: 'Servicios al Socio',
    orden: 210,
  },
  {
    id: 'concesiones',
    label: 'Concesiones',
    href: '/admin/concesiones',
    icon: 'Store',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'concesiones',
    espacio: 'operacion',
    grupo: 'Servicios al Socio',
    orden: 220,
  },
  {
    id: 'utileria',
    label: 'Utilería',
    href: '/admin/utileria',
    icon: 'Shirt',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'utileria',
    espacio: 'operacion',
    grupo: 'Servicios al Socio',
    orden: 230,
  },
  {
    id: 'solicitudes',
    label: 'Solicitudes',
    href: '/admin/solicitudes',
    icon: 'Inbox',
    capa: 'cross_vertical',
    estado: 'proximamente',
    modulo_slug: 'solicitudes',
    espacio: 'operacion',
    grupo: 'Servicios al Socio',
    orden: 240,
  },
  {
    id: 'nominas-externas',
    label: 'Nóminas externas',
    href: '/admin/nominas-externas',
    icon: 'FileSpreadsheet',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'nominas_externas',
    espacio: 'operacion',
    grupo: 'Servicios al Socio',
    orden: 250,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: GESTIÓN
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Finanzas —
  {
    id: 'finanzas',
    label: 'Finanzas',
    href: '/admin/finanzas',
    icon: 'TrendingUp',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.read',
    espacio: 'gestion',
    grupo: 'Finanzas',
    orden: 10,
  },
  {
    id: 'reportes-contables',
    label: 'Reportes contables',
    href: '/admin/finanzas/reportes/libro-mayor',
    icon: 'FileText',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.read',
    espacio: 'gestion',
    grupo: 'Finanzas',
    orden: 20,
  },
  {
    id: 'conciliacion',
    label: 'Conciliación bancaria',
    href: '/admin/finanzas/conciliacion',
    icon: 'GitMerge',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.conciliacion',
    espacio: 'gestion',
    grupo: 'Finanzas',
    orden: 30,
  },
  {
    id: 'plan-cuentas',
    label: 'Plan de cuentas',
    href: '/admin/finanzas/plan-cuentas',
    icon: 'BookOpen',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.admin',
    espacio: 'gestion',
    grupo: 'Finanzas',
    orden: 40,
  },
  {
    id: 'periodos',
    label: 'Períodos contables',
    href: '/admin/finanzas/periodos',
    icon: 'CalendarDays',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.admin',
    espacio: 'gestion',
    grupo: 'Finanzas',
    orden: 50,
  },

  // — GRUPO: PIM —
  {
    id: 'productos',
    label: 'Productos / Servicios',
    href: '/admin/productos',
    icon: 'Package',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'gestion',
    grupo: 'PIM',
    orden: 60,
  },
  {
    id: 'categorias',
    label: 'Categorías',
    href: '/admin/productos/categorias',
    icon: 'FolderTree',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'gestion',
    grupo: 'PIM',
    orden: 70,
  },
  {
    id: 'marcas',
    label: 'Marcas',
    href: '/admin/productos/marcas',
    icon: 'Bookmark',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'gestion',
    grupo: 'PIM',
    orden: 80,
  },
  {
    id: 'precios',
    label: 'Listas de precios',
    href: '/admin/productos/listas-precios',
    icon: 'Tag',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'gestion',
    grupo: 'PIM',
    orden: 90,
  },
  {
    id: 'depositos',
    label: 'Depósitos / Stock',
    href: '/admin/productos/depositos',
    icon: 'Warehouse',
    capa: 'cross_vertical',
    estado: 'proximamente',
    capability_requerida: 'inventario.read',
    espacio: 'gestion',
    grupo: 'PIM',
    orden: 100,
  },
  {
    id: 'proveedores',
    label: 'Proveedores',
    href: '/admin/proveedores',
    icon: 'Truck',
    capa: 'cross_vertical',
    estado: 'proximamente',
    modulo_slug: 'proveedores',
    espacio: 'gestion',
    grupo: 'PIM',
    orden: 110,
  },

  // — GRUPO: Reportes Deportivos —
  {
    id: 'reportes-deportivos',
    label: 'Reportes deportivos',
    href: '/admin/reportes-deportivos',
    icon: 'BarChart3',
    capa: 'vertical_ccbp',
    estado: 'activo',
    espacio: 'gestion',
    grupo: 'Reportes Deportivos',
    orden: 120,
  },
  {
    id: 'stats-jugadores',
    label: 'Estadísticas jugadores',
    href: '/admin/competencias/stats/jugadores',
    icon: 'BarChart',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'partidos',
    espacio: 'gestion',
    grupo: 'Reportes Deportivos',
    orden: 130,
  },
  {
    id: 'stats-equipos',
    label: 'Estadísticas equipos',
    href: '/admin/competencias/stats/equipos',
    icon: 'BarChart2',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'equipos',
    espacio: 'gestion',
    grupo: 'Reportes Deportivos',
    orden: 140,
  },

  // — GRUPO: Proyectos —
  {
    id: 'proyectos',
    label: 'Proyectos',
    href: '/admin/proyectos',
    icon: 'FolderKanban',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'proyectos',
    capability_requerida: 'proyectos.read',
    espacio: 'gestion',
    grupo: 'Proyectos',
    orden: 150,
  },
  {
    id: 'tareas',
    label: 'Tareas',
    href: '/admin/proyectos/tareas',
    icon: 'CheckSquare',
    capa: 'troncal',
    estado: 'proximamente',
    modulo_slug: 'proyectos',
    capability_requerida: 'proyectos.read',
    espacio: 'gestion',
    grupo: 'Proyectos',
    orden: 160,
  },

  // — GRUPO: Dashboards —
  {
    id: 'dashboard-socios',
    label: 'Dashboard socios',
    href: '/admin/membresias/dashboard',
    icon: 'LineChart',
    capa: 'troncal',
    estado: 'activo',
    espacio: 'gestion',
    grupo: 'Dashboards',
    orden: 170,
  },
  {
    id: 'dashboard-general',
    label: 'Dashboard general',
    href: '/admin/dashboards',
    icon: 'Gauge',
    capa: 'troncal',
    estado: 'proximamente',
    espacio: 'gestion',
    grupo: 'Dashboards',
    orden: 180,
  },

  // — GRUPO: RRHH —
  {
    id: 'rrhh',
    label: 'RRHH',
    href: '/admin/rrhh',
    icon: 'Briefcase',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'rrhh',
    capability_requerida: 'rrhh.read',
    espacio: 'gestion',
    grupo: 'RRHH',
    orden: 190,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: SETUP
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Usuarios —
  {
    id: 'usuarios',
    label: 'Usuarios y permisos',
    href: '/admin/configuracion/usuarios',
    icon: 'UserCog',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.users',
    espacio: 'setup',
    grupo: 'Usuarios',
    orden: 10,
  },

  // — GRUPO: Configuración —
  {
    id: 'modulos',
    label: 'Módulos del tenant',
    href: '/admin/marketplace',
    icon: 'Boxes',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.modulos',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 20,
  },
  {
    id: 'identidad-marca',
    label: 'Identidad y marca',
    href: '/admin/configuracion/branding',
    icon: 'Palette',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 30,
  },
  {
    id: 'sedes',
    label: 'Sedes',
    href: '/admin/configuracion/sedes',
    icon: 'MapPin',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 40,
  },
  {
    id: 'espacios-config',
    label: 'Espacios físicos',
    href: '/admin/configuracion/espacios',
    icon: 'LayoutGrid',
    capa: 'cross_vertical',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    modulo_slug: 'espacios_fisicos',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 50,
  },
  {
    id: 'mapa-club',
    label: 'Mapa del club',
    href: '/admin/club/mapa',
    icon: 'Map',
    capa: 'vertical_ccbp',
    estado: 'activo',
    capability_requerida: 'ccbp.mapa.admin',
    modulo_slug: 'diagramacion_club',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 60,
  },
  {
    id: 'atributos-custom',
    label: 'Atributos custom',
    href: '/admin/configuracion/atributos-custom',
    icon: 'Settings2',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 70,
  },
  {
    id: 'catalogos',
    label: 'Catálogos del sistema',
    href: '/admin/catalogos',
    icon: 'Library',
    capa: 'troncal',
    estado: 'proximamente',
    capability_requerida: 'setup.tenant',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 80,
  },
  {
    id: 'configuracion-general',
    label: 'Configuración general',
    href: '/admin/configuracion',
    icon: 'Settings',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'setup',
    grupo: 'Configuración',
    orden: 90,
  },

  // — GRUPO: Integraciones —
  {
    id: 'integraciones',
    label: 'Integraciones',
    href: '/admin/integraciones',
    icon: 'Plug',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.integraciones',
    espacio: 'setup',
    grupo: 'Integraciones',
    orden: 100,
  },
]
