import type { SidebarItem } from './types'

export const SIDEBAR_CATALOG: SidebarItem[] = [
  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: INICIO
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Principal —
  {
    id: 'inicio',
    label: 'Inicio',
    href: '/admin',
    icon: 'Home',
    capa: 'troncal',
    estado: 'activo',
    espacio: 'inicio',
    grupo: 'Principal',
    orden: 10,
  },
  {
    id: 'calendario',
    label: 'Calendario',
    href: '/admin/calendario',
    icon: 'Calendar',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'eventos_calendario',
    espacio: 'inicio',
    grupo: 'Principal',
    orden: 20,
  },
  {
    id: 'notificaciones',
    label: 'Notificaciones',
    href: '/admin/notificaciones',
    icon: 'Bell',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'notificaciones',
    espacio: 'inicio',
    grupo: 'Principal',
    orden: 30,
  },
  {
    id: 'mis-tareas',
    label: 'Mis tareas',
    href: '/admin/mis-tareas',
    icon: 'CheckSquare',
    capa: 'troncal',
    estado: 'proximamente',
    modulo_slug: 'proyectos',
    espacio: 'inicio',
    grupo: 'Principal',
    orden: 40,
  },

  // — GRUPO: Mi cuenta —
  {
    id: 'mi-perfil',
    label: 'Mi perfil',
    href: '/admin/mi-perfil',
    icon: 'User',
    capa: 'troncal',
    estado: 'activo',
    espacio: 'inicio',
    grupo: 'Mi cuenta',
    orden: 50,
  },
  {
    id: 'mi-equipo',
    label: 'Mi equipo',
    href: '/admin/mi-equipo',
    icon: 'Users',
    capa: 'troncal',
    estado: 'activo',
    espacio: 'inicio',
    grupo: 'Mi cuenta',
    orden: 60,
  },
  {
    id: 'mi-cuenta',
    label: 'Mi cuenta',
    href: '/admin/mi-cuenta',
    icon: 'IdCard',
    capa: 'troncal',
    estado: 'activo',
    espacio: 'inicio',
    grupo: 'Mi cuenta',
    orden: 70,
  },

  // — GRUPO: Dashboards —
  {
    id: 'dashboard-general',
    label: 'Dashboard general',
    href: '/admin/dashboards',
    icon: 'Gauge',
    capa: 'troncal',
    estado: 'proximamente',
    espacio: 'inicio',
    grupo: 'Dashboards',
    orden: 80,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: PERSONAS
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Padron —
  {
    id: 'personas',
    label: 'Personas',
    href: '/admin/personas',
    icon: 'Users',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'personas.read',
    espacio: 'personas',
    grupo: 'Padron',
    orden: 10,
  },
  {
    id: 'entidades',
    label: 'Entidades',
    href: '/admin/entidades',
    icon: 'Building2',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'entidades.read',
    espacio: 'personas',
    grupo: 'Padron',
    orden: 20,
  },
  {
    id: 'padrones',
    label: 'Padrones',
    href: '/admin/padrones',
    icon: 'UsersRound',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'personas.read',
    espacio: 'personas',
    grupo: 'Padron',
    orden: 30,
  },

  // — GRUPO: Membresias —
  {
    id: 'membresias',
    label: 'Membresias',
    href: '/admin/membresias',
    icon: 'IdCard',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'cuotas_recurrentes',
    espacio: 'personas',
    grupo: 'Membresias',
    orden: 40,
  },
  {
    id: 'cobranzas',
    label: 'Cobranzas',
    href: '/admin/finanzas/cuotas',
    icon: 'DollarSign',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'cuotas_recurrentes',
    espacio: 'personas',
    grupo: 'Membresias',
    orden: 50,
  },

  // — GRUPO: Control de acceso —
  {
    id: 'acceso',
    label: 'Acceso al club',
    href: '/admin/acceso',
    icon: 'KeyRound',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'acceso',
    espacio: 'personas',
    grupo: 'Control de acceso',
    orden: 60,
  },

  // — GRUPO: Datos medicos —
  {
    id: 'salud',
    label: 'Salud / Lesiones',
    href: '/admin/salud',
    icon: 'Heart',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'datos_medicos',
    capability_requerida: 'ccbp.salud.read_basic',
    espacio: 'personas',
    grupo: 'Datos medicos',
    orden: 70,
  },
  {
    id: 'trayectoria',
    label: 'Historial / Trayectoria',
    href: '/admin/personas',
    icon: 'History',
    capa: 'vertical_ccbp',
    estado: 'activo',
    capability_requerida: 'ccbp.plantel.read',
    nota: 'Se gestiona en el tab Trayectoria de cada persona.',
    espacio: 'personas',
    grupo: 'Datos medicos',
    orden: 80,
  },

  // — GRUPO: Servicios —
  {
    id: 'solicitudes',
    label: 'Solicitudes',
    href: '/admin/solicitudes',
    icon: 'Inbox',
    capa: 'cross_vertical',
    estado: 'proximamente',
    modulo_slug: 'solicitudes',
    espacio: 'personas',
    grupo: 'Servicios',
    orden: 90,
  },
  {
    id: 'nominas-externas',
    label: 'Nominas externas',
    href: '/admin/nominas-externas',
    icon: 'FileSpreadsheet',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'nominas_externas',
    espacio: 'personas',
    grupo: 'Padron externo',
    orden: 100,
  },
  {
    id: 'concesiones',
    label: 'Concesiones',
    href: '/admin/concesiones',
    icon: 'Store',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'concesiones',
    espacio: 'personas',
    grupo: 'Operadores externos',
    orden: 110,
  },

  // — GRUPO: Equipo / RRHH —
  {
    id: 'rrhh',
    label: 'RRHH',
    href: '/admin/rrhh',
    icon: 'Briefcase',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'rrhh',
    capability_requerida: 'rrhh.read',
    espacio: 'personas',
    grupo: 'Equipo / RRHH',
    orden: 120,
  },

  // — GRUPO: Dashboards —
  {
    id: 'dashboard-socios',
    label: 'Dashboard socios',
    href: '/admin/membresias/dashboard',
    icon: 'LineChart',
    capa: 'troncal',
    estado: 'activo',
    espacio: 'personas',
    grupo: 'Dashboards',
    orden: 130,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: ACTIVIDAD
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Equipos —
  {
    id: 'equipos',
    label: 'Equipos',
    href: '/admin/equipos',
    icon: 'Users2',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'equipos',
    espacio: 'actividad',
    grupo: 'Equipos',
    orden: 10,
  },

  // — GRUPO: Planificacion —
  {
    id: 'planificadores',
    label: 'Planificadores',
    href: '/admin/planificadores/semanal',
    icon: 'CalendarRange',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'planificadores',
    espacio: 'actividad',
    grupo: 'Planificacion',
    orden: 20,
  },

  // — GRUPO: Eventos —
  {
    id: 'asistencias',
    label: 'Asistencias',
    href: '/admin/planificadores/semanal',
    icon: 'ClipboardCheck',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'asistencias',
    nota: 'Se gestionan desde cada evento del planificador.',
    espacio: 'actividad',
    grupo: 'Eventos',
    orden: 30,
  },

  // — GRUPO: Entrenamientos —
  {
    id: 'entrenamientos',
    label: 'Entrenamientos',
    href: '/admin/planificadores/semanal?tipo=entrenamiento',
    icon: 'Dumbbell',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'entrenamientos',
    nota: 'Se planifican como eventos tipo entrenamiento.',
    espacio: 'actividad',
    grupo: 'Entrenamientos',
    orden: 40,
  },

  // — GRUPO: Partidos —
  {
    id: 'partidos',
    label: 'Partidos',
    href: '/admin/competencias/partidos',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'partidos',
    nota: 'Listado de partidos del club desde competencias.',
    espacio: 'actividad',
    grupo: 'Partidos',
    orden: 50,
  },
  {
    id: 'amistosos',
    label: 'Amistosos',
    href: '/admin/planificadores/semanal?tipo=amistoso',
    icon: 'Swords',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'amistosos',
    nota: 'Se planifican como eventos tipo amistoso.',
    espacio: 'actividad',
    grupo: 'Partidos',
    orden: 60,
  },
  {
    id: 'tactica',
    label: 'Tactica',
    href: '/admin/planificadores/semanal?tipo=partido,amistoso',
    icon: 'Target',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'tactica',
    nota: 'Se configura desde cada partido/amistoso.',
    espacio: 'actividad',
    grupo: 'Partidos',
    orden: 70,
  },

  // — GRUPO: Competencias —
  {
    id: 'competencias',
    label: 'Competencias y torneos',
    href: '/admin/competencias/torneos',
    icon: 'Award',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'torneos',
    espacio: 'actividad',
    grupo: 'Competencias',
    orden: 80,
  },

  // — GRUPO: Scouting —
  {
    id: 'scouting',
    label: 'Scouting',
    href: '/admin/operaciones/scouting',
    icon: 'Search',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'scouting',
    capability_requerida: 'ccbp.scouting.read',
    espacio: 'actividad',
    grupo: 'Scouting',
    orden: 90,
  },

  // — GRUPO: Disciplinas —
  {
    id: 'disciplinas-op',
    label: 'Disciplinas',
    href: '/admin/disciplinas',
    icon: 'LayoutGrid',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    modulo_slug: 'disciplinas',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 100,
  },
  {
    id: 'disc-futbol',
    label: 'Futbol',
    href: '/admin/disciplinas',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'disciplina_futbol',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 101,
  },
  {
    id: 'disc-basquet',
    label: 'Basquet',
    href: '/admin/disciplinas',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 102,
  },
  {
    id: 'disc-hockey',
    label: 'Hockey',
    href: '/admin/disciplinas',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 103,
  },
  {
    id: 'disc-rugby',
    label: 'Rugby',
    href: '/admin/disciplinas',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 104,
  },
  {
    id: 'disc-tenis',
    label: 'Tenis',
    href: '/admin/disciplinas',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 105,
  },
  {
    id: 'disc-padel',
    label: 'Padel',
    href: '/admin/disciplinas',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 106,
  },
  {
    id: 'disc-golf',
    label: 'Golf',
    href: '/admin/disciplinas',
    icon: 'Trophy',
    capa: 'vertical_ccbp',
    estado: 'proximamente',
    espacio: 'actividad',
    grupo: 'Disciplinas',
    orden: 107,
  },

  // — GRUPO: Reportes —
  {
    id: 'reportes-deportivos',
    label: 'Reportes deportivos',
    href: '/admin/reportes-deportivos',
    icon: 'BarChart3',
    capa: 'vertical_ccbp',
    estado: 'activo',
    espacio: 'actividad',
    grupo: 'Reportes',
    orden: 120,
  },
  {
    id: 'stats-jugadores',
    label: 'Estadisticas jugadores',
    href: '/admin/competencias/stats/jugadores',
    icon: 'BarChart',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'partidos',
    espacio: 'actividad',
    grupo: 'Reportes',
    orden: 130,
  },
  {
    id: 'stats-equipos',
    label: 'Estadisticas equipos',
    href: '/admin/competencias/stats/equipos',
    icon: 'BarChart2',
    capa: 'vertical_ccbp',
    estado: 'activo',
    modulo_slug: 'equipos',
    espacio: 'actividad',
    grupo: 'Reportes',
    orden: 140,
  },

  // — GRUPO: Educacion —
  {
    id: 'polo-educativo',
    label: 'Polo educativo',
    href: '/admin/configuracion',
    icon: 'BookOpen',
    capa: 'troncal',
    estado: 'proximamente',
    modulo_slug: 'polo_educativo',
    espacio: 'actividad',
    grupo: 'Educacion',
    orden: 200,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: MARKETING
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Campanas —
  {
    id: 'comunicaciones',
    label: 'Comunicaciones',
    href: '/admin/comunicaciones',
    icon: 'MessageSquare',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'comunicaciones_masivas',
    espacio: 'marketing',
    grupo: 'Campanas',
    orden: 10,
  },

  // — GRUPO: Captura de leads —
  {
    id: 'pre-inscripciones',
    label: 'Pre-inscripciones',
    href: '/admin/pre-inscripciones',
    icon: 'UserPlus',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'pre_inscripciones',
    espacio: 'marketing',
    grupo: 'Captura de leads',
    orden: 20,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: FINANZAS
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Contabilidad —
  {
    id: 'finanzas',
    label: 'Finanzas',
    href: '/admin/finanzas',
    icon: 'TrendingUp',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.read',
    espacio: 'finanzas',
    grupo: 'Contabilidad',
    orden: 10,
  },

  // — GRUPO: Cajas —
  {
    id: 'cajas',
    label: 'Cajas',
    href: '/admin/cajas',
    icon: 'Banknote',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.read',
    espacio: 'finanzas',
    grupo: 'Cajas',
    orden: 20,
  },

  // — GRUPO: Reportes —
  {
    id: 'reportes-contables',
    label: 'Reportes contables',
    href: '/admin/finanzas/reportes/libro-mayor',
    icon: 'FileText',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.read',
    espacio: 'finanzas',
    grupo: 'Reportes',
    orden: 30,
  },

  // — GRUPO: Operacion —
  {
    id: 'conciliacion',
    label: 'Conciliacion bancaria',
    href: '/admin/finanzas/conciliacion',
    icon: 'GitMerge',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.conciliacion',
    espacio: 'finanzas',
    grupo: 'Operacion',
    orden: 40,
  },

  // — GRUPO: Setup contable —
  {
    id: 'plan-cuentas',
    label: 'Plan de cuentas',
    href: '/admin/finanzas/plan-cuentas',
    icon: 'BookOpen',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.admin',
    espacio: 'finanzas',
    grupo: 'Setup contable',
    orden: 50,
  },
  {
    id: 'periodos',
    label: 'Periodos contables',
    href: '/admin/finanzas/periodos',
    icon: 'CalendarDays',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'finanzas',
    capability_requerida: 'finanzas.admin',
    espacio: 'finanzas',
    grupo: 'Setup contable',
    orden: 60,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: RECURSOS
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Productos —
  {
    id: 'productos',
    label: 'Productos / Servicios',
    href: '/admin/productos',
    icon: 'Package',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'recursos',
    grupo: 'Productos',
    orden: 10,
  },
  {
    id: 'categorias',
    label: 'Categorias',
    href: '/admin/productos/categorias',
    icon: 'FolderTree',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'recursos',
    grupo: 'Productos',
    orden: 20,
  },
  {
    id: 'marcas',
    label: 'Marcas',
    href: '/admin/productos/marcas',
    icon: 'Bookmark',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'recursos',
    grupo: 'Productos',
    orden: 30,
  },
  {
    id: 'precios',
    label: 'Listas de precios',
    href: '/admin/productos/listas-precios',
    icon: 'Tag',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'pim.read',
    espacio: 'recursos',
    grupo: 'Productos',
    orden: 40,
  },

  // — GRUPO: Inventario —
  {
    id: 'depositos',
    label: 'Depositos / Stock',
    href: '/admin/productos/depositos',
    icon: 'Warehouse',
    capa: 'cross_vertical',
    estado: 'proximamente',
    capability_requerida: 'inventario.read',
    espacio: 'recursos',
    grupo: 'Inventario',
    orden: 50,
  },
  {
    id: 'utileria',
    label: 'Utileria',
    href: '/admin/utileria',
    icon: 'Shirt',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'utileria',
    espacio: 'recursos',
    grupo: 'Inventario asignable',
    orden: 60,
  },
  {
    id: 'proveedores',
    label: 'Proveedores',
    href: '/admin/proveedores',
    icon: 'Truck',
    capa: 'cross_vertical',
    estado: 'proximamente',
    modulo_slug: 'proveedores',
    espacio: 'recursos',
    grupo: 'Proveedores',
    orden: 70,
  },

  // — GRUPO: Espacios y reservas —
  {
    id: 'reservas',
    label: 'Reservas de canchas',
    href: '/admin/reservas',
    icon: 'LandPlot',
    capa: 'cross_vertical',
    estado: 'activo',
    modulo_slug: 'reservas',
    espacio: 'recursos',
    grupo: 'Espacios y reservas',
    orden: 80,
  },
  {
    id: 'espacios-config',
    label: 'Espacios fisicos',
    href: '/admin/configuracion/espacios',
    icon: 'LayoutGrid',
    capa: 'cross_vertical',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    modulo_slug: 'espacios_fisicos',
    espacio: 'recursos',
    grupo: 'Espacios y reservas',
    orden: 90,
  },
  {
    id: 'mapa-club',
    label: 'Mapa del club',
    href: '/admin/club/mapa',
    icon: 'Map',
    capa: 'vertical_ccbp',
    estado: 'activo',
    capability_requerida: 'ccbp.mapa.admin',
    modulo_slug: 'diagramacion_club',
    espacio: 'recursos',
    grupo: 'Mapa del predio',
    orden: 100,
  },

  // — GRUPO: Proyectos internos —
  {
    id: 'proyectos',
    label: 'Proyectos',
    href: '/admin/proyectos',
    icon: 'FolderKanban',
    capa: 'troncal',
    estado: 'activo',
    modulo_slug: 'proyectos',
    capability_requerida: 'proyectos.read',
    espacio: 'recursos',
    grupo: 'Proyectos internos',
    orden: 110,
  },
  {
    id: 'tareas',
    label: 'Tareas',
    href: '/admin/proyectos/tareas',
    icon: 'CheckSquare',
    capa: 'troncal',
    estado: 'proximamente',
    modulo_slug: 'proyectos',
    capability_requerida: 'proyectos.read',
    espacio: 'recursos',
    grupo: 'Proyectos internos',
    orden: 120,
  },

  // ═══════════════════════════════════════════════════════════════
  // ESPACIO: CONFIGURACION
  // ═══════════════════════════════════════════════════════════════

  // — GRUPO: Usuarios y permisos —
  {
    id: 'usuarios',
    label: 'Usuarios y permisos',
    href: '/admin/configuracion/usuarios',
    icon: 'UserCog',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.users',
    espacio: 'configuracion',
    grupo: 'Usuarios y permisos',
    orden: 10,
  },
  {
    id: 'atributos-custom',
    label: 'Atributos custom',
    href: '/admin/configuracion/atributos-custom',
    icon: 'Settings2',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'configuracion',
    grupo: 'Usuarios y permisos',
    orden: 20,
  },

  // — GRUPO: Modulos —
  {
    id: 'modulos',
    label: 'Modulos del tenant',
    href: '/admin/marketplace',
    icon: 'Boxes',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.modulos',
    modulo_slug: 'saas_marketplace',
    espacio: 'configuracion',
    grupo: 'Modulos',
    orden: 30,
  },

  // — GRUPO: General —
  {
    id: 'identidad-marca',
    label: 'Identidad y marca',
    href: '/admin/configuracion/branding',
    icon: 'Palette',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'configuracion',
    grupo: 'General',
    orden: 40,
  },
  {
    id: 'sedes',
    label: 'Sedes',
    href: '/admin/configuracion/sedes',
    icon: 'MapPin',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'configuracion',
    grupo: 'General',
    orden: 50,
  },
  {
    id: 'catalogos',
    label: 'Catalogos del sistema',
    href: '/admin/catalogos',
    icon: 'Library',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'configuracion',
    grupo: 'General',
    orden: 60,
  },
  {
    id: 'configuracion-general',
    label: 'Configuracion general',
    href: '/admin/configuracion',
    icon: 'Settings',
    capa: 'troncal',
    estado: 'activo',
    capability_requerida: 'setup.tenant',
    espacio: 'configuracion',
    grupo: 'General',
    orden: 70,
  },

  // — GRUPO: Integraciones —
  {
    id: 'integraciones',
    label: 'Integraciones',
    href: '/admin/integraciones',
    icon: 'Plug',
    capa: 'integracion',
    estado: 'activo',
    capability_requerida: 'setup.integraciones',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 200,
  },
  {
    id: 'conector-resend',
    label: 'Conector Resend',
    href: '/admin/integraciones',
    icon: 'MailOpen',
    capa: 'integracion',
    estado: 'activo',
    modulo_slug: 'conector_resend',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 201,
  },
  {
    id: 'conector-mercadopago',
    label: 'Conector MercadoPago',
    href: '/admin/integraciones',
    icon: 'CreditCard',
    capa: 'integracion',
    estado: 'activo',
    modulo_slug: 'conector_mercadopago',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 202,
  },
  {
    id: 'conector-whatsapp',
    label: 'Conector WhatsApp',
    href: '/admin/integraciones',
    icon: 'Zap',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_whatsapp',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 203,
  },
  {
    id: 'conector-afip',
    label: 'Conector AFIP',
    href: '/admin/integraciones',
    icon: 'Banknote',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_afip',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 204,
  },
  {
    id: 'conector-stripe',
    label: 'Conector Stripe',
    href: '/admin/integraciones',
    icon: 'CreditCard',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_stripe',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 205,
  },
  {
    id: 'conector-gcal',
    label: 'Conector Google Calendar',
    href: '/admin/integraciones',
    icon: 'Calendar',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_gcal',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 206,
  },
  {
    id: 'conector-tiendanube',
    label: 'Conector Tiendanube/Shopify',
    href: '/admin/integraciones',
    icon: 'ShoppingCart',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_tiendanube',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 207,
  },
  {
    id: 'conector-cloudflare',
    label: 'Conector Cloudflare R2',
    href: '/admin/integraciones',
    icon: 'Cloud',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_cloudflare_r2',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 208,
  },
  {
    id: 'conector-document-ai',
    label: 'Conector Document AI',
    href: '/admin/integraciones',
    icon: 'FileSearch',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_document_ai',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 209,
  },
  {
    id: 'conector-brevo',
    label: 'Conector Brevo',
    href: '/admin/integraciones',
    icon: 'Send',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_brevo',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 210,
  },
  {
    id: 'conector-telegram',
    label: 'Conector Telegram',
    href: '/admin/integraciones',
    icon: 'Send',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'conector_telegram',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 211,
  },
  {
    id: 'mcp-server',
    label: 'MCP Server',
    href: '/admin/integraciones',
    icon: 'Server',
    capa: 'integracion',
    estado: 'activo',
    modulo_slug: 'mcp_server',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 212,
  },
  {
    id: 'api-publica',
    label: 'API publica',
    href: '/admin/integraciones',
    icon: 'Code',
    capa: 'integracion',
    estado: 'activo',
    modulo_slug: 'api_publica',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 213,
  },
  {
    id: 'app-movil',
    label: 'App movil',
    href: '/admin/integraciones',
    icon: 'Smartphone',
    capa: 'integracion',
    estado: 'activo',
    modulo_slug: 'app_movil_propia',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 214,
  },
  {
    id: 'bot-whatsapp',
    label: 'Bot WhatsApp equipo',
    href: '/admin/integraciones',
    icon: 'MessageSquare',
    capa: 'integracion',
    estado: 'activo',
    modulo_slug: 'bot_whatsapp_equipo',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 215,
  },
  {
    id: 'padron-consolidacion',
    label: 'Padron consolidacion',
    href: '/admin/integraciones',
    icon: 'UsersRound',
    capa: 'integracion',
    estado: 'activo',
    modulo_slug: 'padron_consolidacion',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 216,
  },
  {
    id: 'federacion-hub',
    label: 'Federacion Hub',
    href: '/admin/configuracion',
    icon: 'Globe',
    capa: 'troncal',
    estado: 'proximamente',
    modulo_slug: 'federacion_hub',
    espacio: 'configuracion',
    grupo: 'Integraciones',
    orden: 220,
  },

  // — GRUPO: Verticales —
  {
    id: 'vert-country',
    label: 'Vertical Country',
    href: '/admin/plataforma',
    icon: 'Home',
    capa: 'plataforma_saas',
    estado: 'proximamente',
    modulo_slug: 'vertical_country',
    espacio: 'configuracion',
    grupo: 'Verticales',
    orden: 300,
  },
  {
    id: 'vert-arquitectura',
    label: 'Vertical Arquitectura',
    href: '/admin/plataforma',
    icon: 'Building',
    capa: 'plataforma_saas',
    estado: 'proximamente',
    modulo_slug: 'vertical_arquitectura',
    espacio: 'configuracion',
    grupo: 'Verticales',
    orden: 301,
  },
  {
    id: 'vert-abogacia',
    label: 'Vertical Abogacia',
    href: '/admin/plataforma',
    icon: 'Scale',
    capa: 'plataforma_saas',
    estado: 'proximamente',
    modulo_slug: 'vertical_abogacia',
    espacio: 'configuracion',
    grupo: 'Verticales',
    orden: 302,
  },
  {
    id: 'vert-publicidad',
    label: 'Vertical Publicidad',
    href: '/admin/plataforma',
    icon: 'Megaphone',
    capa: 'plataforma_saas',
    estado: 'proximamente',
    modulo_slug: 'vertical_publicidad',
    espacio: 'configuracion',
    grupo: 'Verticales',
    orden: 303,
  },
  {
    id: 'vert-retail',
    label: 'Vertical Retail',
    href: '/admin/plataforma',
    icon: 'ShoppingCart',
    capa: 'plataforma_saas',
    estado: 'proximamente',
    modulo_slug: 'vertical_retail',
    espacio: 'configuracion',
    grupo: 'Verticales',
    orden: 304,
  },

  // — GRUPO: IA —
  {
    id: 'ia-asistente',
    label: 'Asistente IA embebido',
    href: '/admin/plataforma',
    icon: 'Sparkles',
    capa: 'ia_nativa',
    estado: 'proximamente',
    modulo_slug: 'ia_asistente_embebido',
    espacio: 'configuracion',
    grupo: 'IA',
    orden: 400,
  },
  {
    id: 'ia-resumen',
    label: 'Resumen ejecutivo IA',
    href: '/admin/plataforma',
    icon: 'FileText',
    capa: 'ia_nativa',
    estado: 'proximamente',
    modulo_slug: 'ia_resumen_ejecutivo',
    espacio: 'configuracion',
    grupo: 'IA',
    orden: 401,
  },
  {
    id: 'ia-voz-wa',
    label: 'Acciones por voz WA',
    href: '/admin/plataforma',
    icon: 'Mic',
    capa: 'ia_nativa',
    estado: 'proximamente',
    modulo_slug: 'ia_acciones_voz_wa',
    espacio: 'configuracion',
    grupo: 'IA',
    orden: 402,
  },

  // — GRUPO: Plataforma —
  {
    id: 'saas-marketplace',
    label: 'Marketplace de modulos',
    href: '/admin/plataforma',
    icon: 'Package',
    capa: 'plataforma_saas',
    estado: 'proximamente',
    modulo_slug: 'saas_marketplace',
    espacio: 'configuracion',
    grupo: 'Plataforma',
    orden: 500,
  },
  {
    id: 'saas-white-label',
    label: 'White-label / Branding',
    href: '/admin/plataforma',
    icon: 'Palette',
    capa: 'plataforma_saas',
    estado: 'proximamente',
    modulo_slug: 'saas_white_label',
    espacio: 'configuracion',
    grupo: 'Plataforma',
    orden: 501,
  },
  {
    id: 'api-rest-publica',
    label: 'API REST publica',
    href: '/admin/plataforma',
    icon: 'Code',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'api_rest_publica',
    espacio: 'configuracion',
    grupo: 'Plataforma',
    orden: 502,
  },
  {
    id: 'webhooks-salientes',
    label: 'Webhooks salientes',
    href: '/admin/plataforma',
    icon: 'Webhook',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'webhooks_salientes',
    espacio: 'configuracion',
    grupo: 'Plataforma',
    orden: 503,
  },
  {
    id: 'agent-connector',
    label: 'Agent Connector',
    href: '/admin/plataforma',
    icon: 'Bot',
    capa: 'integracion',
    estado: 'proximamente',
    modulo_slug: 'agent_connector',
    espacio: 'configuracion',
    grupo: 'Plataforma',
    orden: 504,
  },
]
